CREATE DATABASE CS486_Team12_DB
GO

USE CS486_Team12_DB
GO

CREATE TABLE Genres
(
    ID INT PRIMARY KEY,
    name NVARCHAR(50),
    RID INT
);

CREATE TABLE Regions
(
    ID INT PRIMARY KEY,
    name NVARCHAR(50),  
);

CREATE TABLE Songs
(
    ID INT PRIMARY KEY,
    name NVARCHAR(100),
    GID INT,
    streamCount INT CHECK(streamCount >= 0),
    dateAdded DATE
);

CREATE TABLE Singers
(
    ID INT PRIMARY KEY,
    name NVARCHAR(50)
);
GO

ALTER TABLE Genres ADD
CONSTRAINT FK_GENRES_REGIONS
FOREIGN KEY(RID) REFERENCES Regions(ID);

ALTER TABLE Songs ADD
CONSTRAINT FK_SONGS_GENRES
FOREIGN KEY(GID) REFERENCES GENRES(ID);

GO

USE MASTER
DROP DATABASE CS486_Team12_DB;